### ISSUE TITLE
SocketTimeOutException after uploading 1 big file

### ISSUE THREAD

**Issue by TimoVerbrugghe** [wooti/onedrive-java-client#10]
Hi wooti!

Same situation, big folder called Photos (+/- 160 gb) on my Ubuntu home server that I want to upload to OneDrive. After upload failed, I restarted upload, it uploaded one file of 1 GB but then got a SocketTimeOutException error.

Paste is here: http://pastebin.com/ewmZGuFx

Thanks!

**Comment by TimoVerbrugghe** [comment]
Mmmm, not the error always comes back, even if I restart server, delete log or build the script again...

http://pastebin.com/cLmdtx9k

**Comment by wooti** [comment]
I've increased the timeout, not sure why you are hitting it...
I hope that the increased timeout will resolve the problem.
