### ISSUE TITLE
NullPointerException Errors nearing end of big backup

### ISSUE THREAD

**Issue by TimoVerbrugghe** [wooti/onedrive-java-client#9]
Hi wooti!

I have an Ubuntu home server with a folder called Photos on it, which totals around 160 gb. I now want to back up this folder to my OneDrive account with 1 TB of storage.

At around 152 gb of data backed up, the log shows me a lot of NullPointerException errors, after which the log tells me that the backup is finished with +/- 300 tasks that have failed.

You can see a snippet of the log here: http://pastebin.com/8Hg3Ep2r (with 1 of the NullPointerException errors).

Ubuntu 15.10
ZBOX ID-12 with Atom CPU, 2gb of RAM

**Comment by wooti** [comment]
I suspect this happens if onedrive-java-client is not able to recurse into a particular subfolder. I've added some code to prevent the NullPointerException which also logs the specific subfolder it was unable to access.
